services:

  postgres:
    image: postgres:16
    container_name: planning-poker-ms-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: planning-poker-ms
